# Generated by Django 4.0.5 on 2022-06-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
