# Generated by Django 4.0.5 on 2022-06-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
