# Generated by Django 4.0.5 on 2022-06-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gameround_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='long',
        ),
        migrations.AlterField(
            model_name='gameround',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
    ]
