# Generated by Django 4.0.5 on 2022-06-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_gameround_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameround',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_game_round'),
        ),
    ]
