# Generated by Django 4.0.5 on 2022-06-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gameround_id_alter_gameround_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoundLocation',
            fields=[
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.gameround')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='long',
        ),
    ]
