# Generated by Django 4.0.5 on 2022-06-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gameroundlocation_remove_gameround_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroundlocation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameroundlocation',
            name='game_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gameround'),
        ),
        migrations.AlterUniqueTogether(
            name='gameroundlocation',
            unique_together={('game_round', 'lat', 'long')},
        ),
    ]
