# Generated by Django 4.0.5 on 2022-07-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_gameroundlocation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroundlocation',
            name='game_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.gameround'),
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.gameround')),
            ],
        ),
    ]
