# Generated by Django 4.0.5 on 2022-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_gameroundlocation_game_round_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='guessNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
