# Generated by Django 4.0.5 on 2022-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_gameresult_guessnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='didWin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameresult',
            name='ip',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
