# Generated by Django 4.0.5 on 2022-07-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_gameresult_didwin_gameresult_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='timestamp',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
