# Generated by Django 4.0.5 on 2022-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_gameresult_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
