# Generated by Django 4.0.5 on 2022-07-05 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_gameresult_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guessNumber', models.IntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='core.gameround')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
    ]
