# Generated by Django 4.0.5 on 2022-07-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_guess_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guess',
            name='ip',
        ),
    ]
